on:
  pull_request:
    branches:
      - 032802432428-dev
    types: [closed]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'    
    - run: echo ${{ github.ref }}   
    - name: Set environment variables
      run: |
        if [[ ${{ github.ref }} == '032802432428-DEV' ]]; then
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_032802432428_DEV }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_032802432428_DEV   }}" >> $GITHUB_ENV
        elif [[ ${{ github.ref }} == '595657360061-UAT' ]]; then
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_595657360061_UAT }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_595657360061_UAT }}" >> $GITHUB_ENV
        else
          core.setFailed('Unknown branch')
        fi
    # - run: npm install -g npm-cli-login
    # - name: Login to dmv npm registory
    #   run: npm-cli-login -u octocat -p ${{secrets.DMV_GITHUB_PERSONAL_ACCESS_TOKEN}} -e richard.bach@dmv.ca.gov -r https://npm.pkg.github.com
    # - run: npm install 
    # - run: npm run build
    - name: Deploy
      run: aws s3 sync build/ s3://miles-chatbot-${{ github.ref }} --acl public-read