name: Deploy
on:
  pull_request:
    branches:
      - 032802432428-dev
      - 595657360061-uat
    types: [closed]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'    
    - run: echo ${{ github.ref }}   
    - name: Set Environment
      run: |
        if [[ "${{ github.ref }}" == "032802432428-dev" ]]; then
          echo "Setting up dev environment"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_032802432428_DEV }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_032802432428_DEV   }}" >> $GITHUB_ENV
        elif [[ "${{ github.ref }}" == "595657360061-uat" ]]; then
          echo "Setting up uat environment"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_595657360061_UAT }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_595657360061_UAT }}" >> $GITHUB_ENV
        else
          echo 'Unknown branch for deploying to'
        fi
    - name: Determine .env file
      run: |
        cp config/env.${{ github.ref }} ./.env
    - run: npm install -g npm-cli-login
    - name: Login to dmv npm registory
      run: npm-cli-login -u octocat -p ${{secrets.DMV_GITHUB_PERSONAL_ACCESS_TOKEN}} -e richard.bach@dmv.ca.gov -r https://npm.pkg.github.com
    - run: npm install 
    - run: npm run build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        role-duration-seconds: 1200
    - name: Deploy
      run: aws s3 sync build/ s3://miles-chatbot-${{ github.ref }} --acl public-read
