on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Login to dmv npm registory
      run: echo -e "octocat\n${{secrets.DMV_GITHUB_PERSONAL_ACCESS_TOKEN}}\nrichard.bach@dmv.ca.gov" | npm login --registry=https://npm.pkg.github.com    
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Login to dmv npm registory
      run: echo -e "octocat\n${{secrets.DMV_GITHUB_PERSONAL_ACCESS_TOKEN}}\nrichard.bach@dmv.ca.gov" | npm login --registry=https://npm.pkg.github.com    
    - name: Install dependencies
      run: npm install
    - name: Test
      run: npm run test