on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install -g npm-cli-login
    - name: Login to dmv npm registory
      run: npm-cli-login -u octocat -p ${{secrets.DMV_GITHUB_PERSONAL_ACCESS_TOKEN}} -e richard.bach@dmv.ca.gov -r https://npm.pkg.github.com
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install -g npm-cli-login
    - name: Login to dmv npm registory
      run: npm-cli-login -u octocat -p ${{secrets.DMV_GITHUB_PERSONAL_ACCESS_TOKEN}} -e richard.bach@dmv.ca.gov -r https://npm.pkg.github.com
    - name: Install dependencies
      run: npm install
    - name: Test
      run: npm run test